/** \file proto.h

Declaration of all the functions of the FARGO code

*/

void masterprint (const char *template, ...);
void mastererr (const char *template, ...);
real GetGlobalIFrac ();
void prs_exit ();
void *prs_malloc ();
void erreur ();
void message ();
PolarGrid    *CreatePolarGrid();
void MultiplyPolarGridbyConstant ();
void DumpSources ();
Force *AllocateForce ();
void ComputeForce ();
void FreeForce ();
void UpdateLog ();
void UpdateLogSG ();
void ReadfromFile ();
void InitLabel ();
void Initialization ();
void var ();
void ReadVariables ();
void PrintUsage ();
real TellNbOrbits ();
real TellNbOutputs ();
void TellEverything ();
void GiveTimeInfo ();
void InitSpecificTime ();
void GiveSpecificTime ();
void EmptyPlanetSystemFile ();
void WritePlanetFile ();
void WritePlanetSystemFile ();
void WriteBigPlanetFile ();
void WriteBigPlanetSystemFile ();
real GetfromPlanetFile ();
void RestartPlanetarySystem ();
void WriteDiskPolar();
void WriteDim ();
void SendOutput ();
void ComputeIndirectTerm ();
void FillForcesArrays ();
void AdvanceSystemFromDisk ();
void AdvanceSystemRK5 ();
void SolveOrbits ();
real ConstructSequence ();
void InitGasVelocities ();
void AccreteOntoPlanets ();
void FindOrbitalElements ();
int FindNumberOfPlanets ();
PlanetarySystem *AllocPlanetSystem ();
void FreePlanetary ();
PlanetarySystem *InitPlanetarySystem ();
void ListPlanets ();
real GetPsysInfo ();
void RotatePsys ();
void DerivMotionRK5 ();
void TranslatePlanetRK5 ();
void RungeKunta ();
real GasTotalMass();
real GasMomentum ();
real GasTotalEnergy ();
void DivisePolarGrid ();
void InitComputeAccel ();
Pair ComputeAccel ();
void OpenBoundary ();
void NonReflectingBoundary ();
void ApplyOuterSourceMass ();
void ApplyBoundaryCondition ();
void ApplySubKeplerianBoundary ();
void CorrectVtheta ();
boolean DetectCrash ();
void FillPolar1DArrays ();
void InitEuler ();
real min2 ();
real max2 ();
void ActualiseGas ();
void AlgoGas ();
void SubStep1 ();
void SubStep2 ();
void SubStep3 ();
int ConditionCFL ();
real Sigma ();
void FillSigma ();
void RefillSigma ();
real Energy ();
void FillEnergy ();
void RefillEnergy ();
real PrescTime();
void FillPrescTime();
void Transport ();
void OneWindRad ();
void ComputeThetaElongations ();
void ComputeAverageThetaVelocities ();
void ComputeResiduals ();
void ComputeConstantResidual ();
void AdvectSHIFT ();
void OneWindTheta ();
void QuantitiesAdvection ();
void ComputeExtQty ();
void ComputeSpeQty ();
void InitTransport () ;
void ComputeStarRad ();
void ComputeStarTheta ();
void ComputeLRMomenta ();
void ComputeVelocities ();
real VanLeerRadial ();
void VanLeerTheta ();
void InitViscosity ();
void ComputeViscousTerms ();
void UpdateVelocitiesWithViscosity ();
void AllocateComm ();
void CommunicateBoundaries ();
void handfpe();
void setfpe ();
void merge ();
void ReadPrevDim ();
void CheckRebin ();
void SplitDomain ();
void InitVariables();
real FViscosity ();
real DFViscosity ();
real AspectRatio ();
Force ComputeForceStockholm ();
void UpdateLogStockholm ();
Pair MassInOut ();
void CheckMomentumConservation ();
void InitGasDensity();
void InitGasEnergy();
void mpi_make1Dprofile ();
void mpi_makeglobalfield ();
void ComputeDivergenceVelocity ();
void ComputeSoundSpeed ();
void ComputePressureField ();
void ComputeTemperatureField ();
real CircumPlanetaryMass ();
real compute_smoothing ();
void EvanescentBoundary ();
void ComputeViscousHeating ();
void ComputeEntropyDiffusion ();
void ComputeRadiativeDiffusion ();
int SORsolver_RadiativeDiffusion ();
void ChessBoardIndexing ();
int GLOBAL_SORsolver_RadiativeDiffusion ();
void SynchronizeOverlapFields ();
void ComputeRadiativeDiffusionSareh ();
void ComputeThermalCooling ();
void MakeDir ();
FILE *fopenp ();
void ApplyLSAOnPotential ();
void DampDensity ();
void InitImposedDensity ();
void ComputeOpacities ();
void ComputeCodeUnits ();
void SubStep0();
real ComputeBetaCooling();
void Evaporation();
void AddFloorDensity ();
void AddFloorEnergy ();
void EmptyDustSystemFile ();
void WriteDustSystemFile ();
DustSystem *InitDustSystem ();
void FreeDust ();
DustSystem *AllocDustSystem ();
void interpolation();
void newinterpolation();
void UpdateDustVelocities();
void SemiUpdateDustPositions();
void RotateDsys ();
void CreateJacobiFile ();
void WriteJacobi ();
void AccretingBoundary ();
void ApplyPhotoEvaporation ();
void mergedust ();
void RefillDSigma ();
real DSigma ();
void FillDSigma();
void InitDustDensity ();
void InitDustVelocities ();
void ComputeDustSoundSpeedAndPressure ();
real DAspectRatio ();
void SFTAvelocity ();
void Diffd ();
void Transportd ();
void OneWindRadd ();
void OneWindThetad ();
real VanLeerRadiald ();
real VanLeerRadialdd ();
void VanLeerThetad ();
void QuantitiesAdvectiond ();
void OpenBoundaryd ();
void InitDustStokesNumber ();
void InitializeOneDViscousEvolution ();
void SolveOneDViscousEvolution ();
void Write1DViscProfiles ();
void EvanescentBoundaryDust ();
real myrandn_rad ();
real myrandn_phi ();
void ComputeResidualDensity ();
void CompareSGandSummationTorques ();
